import re
import shutil
import subprocess
import sys
from pathlib import Path

from aws_cdk import (
    Duration,
    RemovalPolicy,
    Stack,
)
from aws_cdk import (
    aws_apigateway as apigateway,
)
from aws_cdk import (
    aws_cloudwatch as cloudwatch,
)
from aws_cdk import (
    aws_dynamodb as dynamodb,
)
from aws_cdk import (
    aws_events as events,
)
from aws_cdk import (
    aws_events_targets as targets,
)
from aws_cdk import (
    aws_iam as iam,
)
from aws_cdk import (
    aws_lambda as _lambda,
)
from aws_cdk import (
    aws_lambda_destinations as destinations,
)
from aws_cdk import (
    aws_lambda_event_sources as lambda_event_sources,
)
from aws_cdk import (
    aws_s3 as s3,
)
from aws_cdk import (
    aws_s3_notifications as s3n,
)
from aws_cdk import (
    aws_sns as sns,
)
from aws_cdk import (
    aws_sns_subscriptions as sns_subscriptions,
)
from aws_cdk import (
    aws_sqs as sqs,
)
from constructs import Construct

REPO_ROOT = Path(__file__).resolve().parents[2]
LAMBDAS_DIR = REPO_ROOT / "lambdas"
LAYER_BUILD_ROOT = Path(__file__).resolve().parent / ".layer_build"

DEFAULT_BEDROCK_MODEL_ID = "anthropic.claude-3-5-sonnet-20241022-v2:0"
DEFAULT_BEDROCK_EMBEDDING_MODEL_ID = "amazon.titan-embed-text-v2:0"
DEFAULT_FIT_THRESHOLD = "0.7"

# Placeholders — SES sandbox requires both verified before alerts actually deliver.
# Override at deploy time (e.g. via CDK context) with your own addresses. See
# SETUP.md for the manual SES verification step this requires.
DEFAULT_SENDER_EMAIL = "alerts@example.com"
DEFAULT_RECIPIENT_EMAIL = "candidate@example.com"

# Mirrors common/dynamodb.py's key schema constants. Not imported directly: the CDK app
# runs in infra/.venv, a separate Python environment from the root venv that doesn't
# have common's dependencies (pydantic) installed — infra intentionally doesn't depend
# on application code, only on the plain strings that make up the table's key schema.
PARTITION_KEY = "posting_id"
GSI_NAME = "ScoreIndex"
GSI_PARTITION_KEY = "gsi_pk"
GSI_SORT_KEY = "score"


def _pinned_version(package: str) -> str:
    """Read a package's pinned version out of the root requirements.txt, so the Lambda
    layer we build for it can never silently drift from what's pinned for local dev.
    """
    requirements = (REPO_ROOT / "requirements.txt").read_text()
    match = re.search(rf"^{re.escape(package)}==([^\s;]+)", requirements, re.MULTILINE)
    if not match:
        raise ValueError(f"{package} is not pinned in requirements.txt")
    return match.group(1)


def _build_common_layer_asset() -> str:
    """Copy common/*.py (+ example JSON) and ml/features.py into a Lambda-layer-shaped
    python/ dir.

    A plain file copy, not pip/Docker bundling: common/storage_keys.py has no
    third-party dependency, so it's safe to ship as-is. common/models.py imports
    pydantic, but that import is only exercised by whichever Lambda actually does
    `from common.models import ...` (common/__init__.py has no eager imports) — a Lambda
    that needs it also attaches the PydanticLayer built below.

    ml/features.py (PLAN.md Phase 6) is included too, but deliberately *only* that one
    file, not the rest of ml/ — ml/train.py, ml/dataset.py etc. import scikit-learn/
    xgboost, and features.py itself is pure stdlib beyond `common.models`, so copying
    just it (plus ml/__init__.py to make it a package) gives the threshold Lambda
    (Phase 7) the exact same feature computation training used, without pulling any of
    training's heavy dependencies into the Lambda.
    """
    build_dir = LAYER_BUILD_ROOT / "common"
    python_dir = build_dir / "python"
    common_dir = python_dir / "common"
    ml_dir = python_dir / "ml"
    for existing in (common_dir, ml_dir):
        if existing.exists():
            shutil.rmtree(existing)
    common_dir.mkdir(parents=True)
    ml_dir.mkdir(parents=True)

    for pattern in ("*.py", "*.json"):
        for file_path in (REPO_ROOT / "common").glob(pattern):
            shutil.copy(file_path, common_dir / file_path.name)
    for filename in ("__init__.py", "features.py"):
        shutil.copy(REPO_ROOT / "ml" / filename, ml_dir / filename)

    return str(build_dir)


def _build_threshold_lambda_asset() -> str:
    """Stage lambdas/threshold/*.py plus the trained re-ranker's inference JSON into one
    deployable directory.

    The inference JSON (ml/artifacts/reranker_inference.json) is a training *output*,
    gitignored and regenerated by `python -m ml.train` — it must exist before `cdk
    synth`/`cdk deploy` runs, the same "train offline, deploy the artifact" precondition
    any real ML deployment pipeline has. Its path is hardcoded here rather than imported
    from ml.train (which would pull scikit-learn/xgboost into the infra venv — the same
    dependency-isolation reason the DynamoDB key-schema constants above are duplicated
    rather than imported from common.dynamodb).
    """
    inference_json_path = REPO_ROOT / "ml" / "artifacts" / "reranker_inference.json"
    if not inference_json_path.exists():
        raise FileNotFoundError(
            f"{inference_json_path} not found — run `python -m ml.train` (from the repo "
            "root, with the root .venv active) to train the re-ranker before deploying."
        )

    build_dir = LAYER_BUILD_ROOT / "threshold_lambda"
    if build_dir.exists():
        shutil.rmtree(build_dir)
    build_dir.mkdir(parents=True)

    for file_path in (LAMBDAS_DIR / "threshold").glob("*.py"):
        shutil.copy(file_path, build_dir / file_path.name)
    shutil.copy(inference_json_path, build_dir / "model.json")

    return str(build_dir)


def _build_pydantic_layer_asset() -> str:
    """Download pydantic (+ its compiled pydantic-core dependency) as Lambda-compatible
    manylinux wheels, without Docker.

    pydantic-core ships as a platform-specific compiled wheel (it's written in Rust).
    Building it locally with a plain `pip install --target` on a Mac would silently
    bundle a macOS binary that crashes on Lambda's Linux runtime. Instead, `pip install
    --platform manylinux2014_x86_64 --only-binary=:all:` downloads the prebuilt Linux
    wheel straight from PyPI — no compilation, no Docker — as long as one exists for the
    pinned version (it does for pydantic 2.x). Cached by pinned version so `cdk synth`
    doesn't re-download on every run.
    """
    version = _pinned_version("pydantic")
    build_dir = LAYER_BUILD_ROOT / "pydantic"
    marker = build_dir / f".built-{version}"
    if marker.exists():
        return str(build_dir)

    python_dir = build_dir / "python"
    if python_dir.exists():
        shutil.rmtree(python_dir)
    python_dir.mkdir(parents=True)

    subprocess.run(
        [
            sys.executable,
            "-m",
            "pip",
            "install",
            f"pydantic=={version}",
            "--platform",
            "manylinux2014_x86_64",
            "--implementation",
            "cp",
            "--python-version",
            "3.12",
            "--only-binary=:all:",
            "--target",
            str(python_dir),
        ],
        check=True,
        capture_output=True,
    )
    marker.touch()
    return str(build_dir)


class JobPulseStack(Stack):
    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        # --- Raw postings landing zone (PLAN.md Phase 2.2) ---
        # Immutable audit trail: every posting a source returns lands here untouched,
        # keyed by common.storage_keys.raw_posting_key. Also holds the extraction
        # Lambda's structured/ output (PLAN.md Phase 3) until Phase 5 adds DynamoDB.
        raw_postings_bucket = s3.Bucket(
            self,
            "RawPostingsBucket",
            removal_policy=RemovalPolicy.DESTROY,  # dev default; use RETAIN in prod
            auto_delete_objects=True,
            block_public_access=s3.BlockPublicAccess.BLOCK_ALL,
        )

        # --- Structured store (PLAN.md Phase 5) ---
        # Stream enabled so the embed Lambda can react to newly-extracted postings
        # (NEW_IMAGE is enough — embed only needs the item's current field values, not
        # what changed). PAY_PER_REQUEST: postings/day volume is low and spiky (bursts
        # on each 6-hour ingestion cycle), not steady enough to right-size provisioned
        # capacity for.
        postings_table = dynamodb.Table(
            self,
            "PostingsTable",
            partition_key=dynamodb.Attribute(
                name=PARTITION_KEY, type=dynamodb.AttributeType.STRING
            ),
            billing_mode=dynamodb.BillingMode.PAY_PER_REQUEST,
            removal_policy=RemovalPolicy.DESTROY,  # dev default; use RETAIN in prod
            stream=dynamodb.StreamViewType.NEW_IMAGE,
        )
        postings_table.add_global_secondary_index(
            index_name=GSI_NAME,
            partition_key=dynamodb.Attribute(
                name=GSI_PARTITION_KEY, type=dynamodb.AttributeType.STRING
            ),
            sort_key=dynamodb.Attribute(name=GSI_SORT_KEY, type=dynamodb.AttributeType.NUMBER),
            projection_type=dynamodb.ProjectionType.ALL,
        )

        # --- Shared data-contracts layer, consumed by every Lambda (Phase 1 code) ---
        common_layer = _lambda.LayerVersion(
            self,
            "CommonLayer",
            code=_lambda.Code.from_asset(_build_common_layer_asset()),
            compatible_runtimes=[_lambda.Runtime.PYTHON_3_12],
            description="Shared JobPulse data contracts (common/ package)",
        )

        # --- Third-party dependency layer, for Lambdas that need common.models ---
        pydantic_layer = _lambda.LayerVersion(
            self,
            "PydanticLayer",
            code=_lambda.Code.from_asset(_build_pydantic_layer_asset()),
            compatible_runtimes=[_lambda.Runtime.PYTHON_3_12],
            compatible_architectures=[_lambda.Architecture.X86_64],
            description="pydantic + pydantic-core (manylinux x86_64 wheels)",
        )

        # --- Ingestion Lambda (PLAN.md Phase 2.1) ---
        fetch_lambda = _lambda.Function(
            self,
            "FetchLambda",
            runtime=_lambda.Runtime.PYTHON_3_12,
            architecture=_lambda.Architecture.X86_64,
            handler="handler.handler",
            code=_lambda.Code.from_asset(str(LAMBDAS_DIR / "fetch")),
            layers=[common_layer],
            timeout=Duration.seconds(30),
            memory_size=256,
            tracing=_lambda.Tracing.ACTIVE,
            environment={
                "RAW_BUCKET_NAME": raw_postings_bucket.bucket_name,
                "JOB_SOURCE": "remoteok",
            },
        )
        raw_postings_bucket.grant_write(fetch_lambda)

        # --- Scheduled trigger (PLAN.md Phase 2.3) ---
        events.Rule(
            self,
            "FetchScheduleRule",
            schedule=events.Schedule.rate(Duration.hours(6)),
            targets=[targets.LambdaFunction(fetch_lambda)],
        )

        # --- Extraction DLQ (PLAN.md Phase 12.1) ---
        # S3 invokes extract_lambda *asynchronously*, so Lambda's own built-in async
        # retry (retry_attempts below) and Destinations (on_failure) apply directly to
        # the function itself — a fundamentally different mechanism from embed's
        # DynamoDB-Streams-sourced DLQ further down, which is configured on the event
        # source mapping instead, since a stream poller manages its own retries.
        extract_dlq = sqs.Queue(self, "ExtractDlq", retention_period=Duration.days(14))

        # --- Extraction Lambda (PLAN.md Phase 3) ---
        extract_lambda = _lambda.Function(
            self,
            "ExtractLambda",
            runtime=_lambda.Runtime.PYTHON_3_12,
            architecture=_lambda.Architecture.X86_64,
            handler="handler.handler",
            code=_lambda.Code.from_asset(str(LAMBDAS_DIR / "extract")),
            layers=[common_layer, pydantic_layer],
            timeout=Duration.seconds(60),  # allows for the Bedrock call + one retry
            memory_size=512,
            tracing=_lambda.Tracing.ACTIVE,
            # Lambda's own async-invoke retry (AWS-managed backoff between attempts,
            # not a formula we configure directly) tries up to twice more before
            # giving up, or up to 2 hours after the original invocation — whichever
            # comes first — then delivers the failed event + error details to the DLQ.
            retry_attempts=2,
            max_event_age=Duration.hours(2),
            on_failure=destinations.SqsDestination(extract_dlq),
            environment={
                "BEDROCK_MODEL_ID": DEFAULT_BEDROCK_MODEL_ID,
                "POSTINGS_TABLE_NAME": postings_table.table_name,
            },
        )
        # Least privilege: read only the raw/ prefix it consumes from S3. It only ever
        # creates new DynamoDB items (one per posting_id, set once at extraction time),
        # never reads or modifies an existing one — PutItem only, not grant_write_data's
        # broader PutItem/UpdateItem/DeleteItem/BatchWriteItem set.
        extract_lambda.add_to_role_policy(
            iam.PolicyStatement(
                actions=["s3:GetObject"],
                resources=[raw_postings_bucket.arn_for_objects("raw/*")],
            )
        )
        extract_lambda.add_to_role_policy(
            iam.PolicyStatement(
                actions=["dynamodb:PutItem"],
                resources=[postings_table.table_arn],
            )
        )
        extract_lambda.add_to_role_policy(
            iam.PolicyStatement(
                actions=["bedrock:InvokeModel"],
                resources=[
                    f"arn:aws:bedrock:{self.region}::foundation-model/anthropic.*"
                ],
            )
        )

        # --- Event-driven trigger: new raw posting -> extract (PLAN.md Phase 3) ---
        raw_postings_bucket.add_event_notification(
            s3.EventType.OBJECT_CREATED,
            s3n.LambdaDestination(extract_lambda),
            s3.NotificationKeyFilter(prefix="raw/", suffix=".json"),
        )

        # --- Embedding Lambda (PLAN.md Phase 4, trigger + persistence updated in Phase 5) ---
        embed_lambda = _lambda.Function(
            self,
            "EmbedLambda",
            runtime=_lambda.Runtime.PYTHON_3_12,
            architecture=_lambda.Architecture.X86_64,
            handler="handler.handler",
            code=_lambda.Code.from_asset(str(LAMBDAS_DIR / "embed")),
            layers=[common_layer, pydantic_layer],
            timeout=Duration.seconds(60),
            memory_size=512,
            tracing=_lambda.Tracing.ACTIVE,
            environment={
                "BEDROCK_EMBEDDING_MODEL_ID": DEFAULT_BEDROCK_EMBEDDING_MODEL_ID,
                "POSTINGS_TABLE_NAME": postings_table.table_name,
                "RAW_BUCKET_NAME": raw_postings_bucket.bucket_name,
            },
        )
        # Least privilege: only the candidate/ cache prefix needs S3 access now — the
        # posting itself arrives via the DynamoDB stream, and the embedding/similarity
        # go back via UpdateItem, not an S3 write.
        embed_lambda.add_to_role_policy(
            iam.PolicyStatement(
                actions=["s3:GetObject", "s3:PutObject"],
                resources=[raw_postings_bucket.arn_for_objects("candidate/*")],
            )
        )
        # UpdateItem only, not PutItem: this Lambda only ever patches a row extraction
        # already created, never creates one — the exact inverse of extraction's grant.
        embed_lambda.add_to_role_policy(
            iam.PolicyStatement(
                actions=["dynamodb:UpdateItem"],
                resources=[postings_table.table_arn],
            )
        )
        embed_lambda.add_to_role_policy(
            iam.PolicyStatement(
                actions=["bedrock:InvokeModel"],
                resources=[
                    f"arn:aws:bedrock:{self.region}::foundation-model/amazon.titan-embed*"
                ],
            )
        )

        # --- Embedding DLQ (PLAN.md Phase 12.1) ---
        # A DynamoDB-Streams-sourced DLQ message carries only *batch metadata* (shard
        # id, sequence range) — never the failed record's content, since stream data
        # can roll off before a redrive happens. See lambdas/dlq_redrive/handler.py's
        # docstring for how redriving this queue actually works as a result.
        embed_dlq = sqs.Queue(self, "EmbedDlq", retention_period=Duration.days(14))

        # --- Event-driven trigger: new posting row -> embed (PLAN.md Phase 5) ---
        # INSERT-only filter: this Lambda's own UpdateItem calls produce MODIFY stream
        # records, which the filter excludes, so it can never re-trigger itself.
        # add_event_source also grants the stream-read permissions (DescribeStream,
        # GetRecords, GetShardIterator, ListStreams) automatically.
        embed_lambda.add_event_source(
            lambda_event_sources.DynamoEventSource(
                postings_table,
                starting_position=_lambda.StartingPosition.LATEST,
                batch_size=1,
                retry_attempts=2,
                on_failure=lambda_event_sources.SqsDlq(embed_dlq),
                filters=[
                    _lambda.FilterCriteria.filter(
                        {"eventName": _lambda.FilterRule.is_equal("INSERT")}
                    )
                ],
            )
        )

        # --- Alerts topic (PLAN.md Phase 7.2) ---
        # A separate SNS topic (rather than the threshold Lambda calling SES directly)
        # is what makes "later, an additional subscriber" (spec section 5.3 — e.g. a
        # future Slack/Discord webhook) free: it would attach to this same topic without
        # touching the threshold Lambda or the alert_email Lambda below at all.
        alerts_topic = sns.Topic(self, "AlertsTopic", display_name="JobPulse fit alerts")

        # --- Scoring + threshold Lambda (PLAN.md Phase 7.1) ---
        threshold_lambda = _lambda.Function(
            self,
            "ThresholdLambda",
            runtime=_lambda.Runtime.PYTHON_3_12,
            architecture=_lambda.Architecture.X86_64,
            handler="handler.handler",
            code=_lambda.Code.from_asset(_build_threshold_lambda_asset()),
            layers=[common_layer, pydantic_layer],
            timeout=Duration.seconds(30),
            memory_size=256,
            tracing=_lambda.Tracing.ACTIVE,
            environment={
                "POSTINGS_TABLE_NAME": postings_table.table_name,
                "ALERTS_TOPIC_ARN": alerts_topic.topic_arn,
                "FIT_THRESHOLD": DEFAULT_FIT_THRESHOLD,
            },
        )
        # UpdateItem only — same reasoning as the embed Lambda's grant above.
        threshold_lambda.add_to_role_policy(
            iam.PolicyStatement(
                actions=["dynamodb:UpdateItem"],
                resources=[postings_table.table_arn],
            )
        )
        alerts_topic.grant_publish(threshold_lambda)

        # --- Event-driven trigger: embedding just landed -> threshold (PLAN.md Phase 7) ---
        # This Lambda must run *after* embed (it needs embedding_similarity as a
        # feature) but embed's own write is also a MODIFY — eventName alone can't tell
        # "embed just finished" apart from "threshold already finished" the way
        # INSERT-vs-MODIFY could in Phase 5. The extra conditions do that instead:
        # `embedding` (a Binary attribute) existing means embed has run; `score` still
        # being NULL means threshold hasn't. Once threshold sets a real score, this
        # same filter excludes its own MODIFY — no self-trigger, same principle as
        # Phase 5's embed trigger, expressed with a finer-grained filter.
        threshold_lambda.add_event_source(
            lambda_event_sources.DynamoEventSource(
                postings_table,
                starting_position=_lambda.StartingPosition.LATEST,
                batch_size=1,
                retry_attempts=2,
                filters=[
                    _lambda.FilterCriteria.filter(
                        {
                            "eventName": ["MODIFY"],
                            "dynamodb": {
                                "NewImage": {
                                    "embedding": {"B": [{"exists": True}]},
                                    "score": {"NULL": [True]},
                                }
                            },
                        }
                    )
                ],
            )
        )

        # --- Alert email Lambda (PLAN.md Phase 7.2-3) ---
        # CommonLayer only (not PydanticLayer): common.logging_utils/common.metrics
        # (PLAN.md Phase 9) are pure stdlib, so no pydantic needed here.
        alert_email_lambda = _lambda.Function(
            self,
            "AlertEmailLambda",
            runtime=_lambda.Runtime.PYTHON_3_12,
            architecture=_lambda.Architecture.X86_64,
            handler="handler.handler",
            code=_lambda.Code.from_asset(str(LAMBDAS_DIR / "alert_email")),
            layers=[common_layer],
            timeout=Duration.seconds(15),
            memory_size=128,
            tracing=_lambda.Tracing.ACTIVE,
            environment={
                "SENDER_EMAIL": self.node.try_get_context("senderEmail") or DEFAULT_SENDER_EMAIL,
                "RECIPIENT_EMAIL": self.node.try_get_context("recipientEmail")
                or DEFAULT_RECIPIENT_EMAIL,
            },
        )
        # SES has no per-identity resource ARN known until an identity is manually
        # verified (see SETUP.md), so this is scoped to the action rather than a
        # specific identity resource.
        alert_email_lambda.add_to_role_policy(
            iam.PolicyStatement(actions=["ses:SendEmail", "ses:SendRawEmail"], resources=["*"])
        )
        alerts_topic.add_subscription(sns_subscriptions.LambdaSubscription(alert_email_lambda))

        # --- Query API Lambda (PLAN.md Phase 8.1) ---
        query_api_lambda = _lambda.Function(
            self,
            "QueryApiLambda",
            runtime=_lambda.Runtime.PYTHON_3_12,
            architecture=_lambda.Architecture.X86_64,
            handler="handler.handler",
            code=_lambda.Code.from_asset(str(LAMBDAS_DIR / "query_api")),
            layers=[common_layer, pydantic_layer],
            timeout=Duration.seconds(10),
            memory_size=256,
            tracing=_lambda.Tracing.ACTIVE,
            environment={"POSTINGS_TABLE_NAME": postings_table.table_name},
        )
        # Read-only, and only the one action this Lambda actually calls — not
        # grant_read_data()'s broader GetItem/Scan/BatchGetItem/etc. set. The GSI's
        # items are addressed via "{table_arn}/index/*", a separate resource from the
        # base table for IAM purposes even though it's the same physical table.
        query_api_lambda.add_to_role_policy(
            iam.PolicyStatement(
                actions=["dynamodb:Query"],
                resources=[postings_table.table_arn, f"{postings_table.table_arn}/index/*"],
            )
        )

        # --- API Gateway (PLAN.md Phase 8.2) ---
        # REST API (not the newer HTTP API) specifically because it has native API key
        # + usage plan support for simple access gating — HTTP API doesn't. A Cognito
        # authorizer would be the heavier alternative the spec also allows; unnecessary
        # for a single-candidate demo API.
        query_api = apigateway.LambdaRestApi(
            self,
            "QueryApi",
            handler=query_api_lambda,
            proxy=True,
            default_method_options=apigateway.MethodOptions(api_key_required=True),
            deploy_options=apigateway.StageOptions(tracing_enabled=True),
        )
        query_api_key = query_api.add_api_key("QueryApiKey")
        usage_plan = query_api.add_usage_plan(
            "QueryApiUsagePlan",
            api_stages=[
                apigateway.UsagePlanPerApiStage(api=query_api, stage=query_api.deployment_stage)
            ],
        )
        usage_plan.add_api_key(query_api_key)

        # --- DLQ redrive Lambda (PLAN.md Phase 12.4) ---
        # Manually invoked (never triggered automatically) after investigating and
        # fixing whatever caused failures — see lambdas/dlq_redrive/handler.py's
        # docstring for why extraction and embedding are redriven differently.
        dlq_redrive_lambda = _lambda.Function(
            self,
            "DlqRedriveLambda",
            runtime=_lambda.Runtime.PYTHON_3_12,
            architecture=_lambda.Architecture.X86_64,
            handler="handler.handler",
            code=_lambda.Code.from_asset(str(LAMBDAS_DIR / "dlq_redrive")),
            layers=[common_layer],
            timeout=Duration.minutes(2),
            memory_size=256,
            tracing=_lambda.Tracing.ACTIVE,
            environment={
                "EXTRACT_DLQ_URL": extract_dlq.queue_url,
                "EMBED_DLQ_URL": embed_dlq.queue_url,
                "EXTRACT_FUNCTION_NAME": extract_lambda.function_name,
                "EMBED_FUNCTION_NAME": embed_lambda.function_name,
                "POSTINGS_TABLE_NAME": postings_table.table_name,
            },
        )
        extract_dlq.grant_consume_messages(dlq_redrive_lambda)
        embed_dlq.grant_consume_messages(dlq_redrive_lambda)
        extract_lambda.grant_invoke(dlq_redrive_lambda)
        embed_lambda.grant_invoke(dlq_redrive_lambda)
        # Scan only, and only this table: an operator-triggered maintenance path run
        # infrequently, not the query API's hot path — a table scan here is fine.
        dlq_redrive_lambda.add_to_role_policy(
            iam.PolicyStatement(actions=["dynamodb:Scan"], resources=[postings_table.table_arn])
        )

        # --- Alarms (PLAN.md Phase 9.2, DLQ depth added in Phase 12.3) ---
        # Every core-pipeline Lambda gets the same two alarms: an error-rate alarm
        # (errors as a percentage of invocations, not a raw count — a fixed count
        # means something different for a Lambda invoked twice a day vs. one invoked
        # constantly) and a duration alarm at 80% of that Lambda's own configured
        # timeout (an early warning before it starts actually timing out).
        pipeline_lambdas = {
            "Fetch": (fetch_lambda, fetch_lambda.timeout),
            "Extract": (extract_lambda, extract_lambda.timeout),
            "Embed": (embed_lambda, embed_lambda.timeout),
            "Threshold": (threshold_lambda, threshold_lambda.timeout),
            "AlertEmail": (alert_email_lambda, alert_email_lambda.timeout),
            "QueryApi": (query_api_lambda, query_api_lambda.timeout),
        }

        def add_lambda_alarms(fn: _lambda.Function, id_prefix: str, timeout: Duration) -> None:
            error_rate = cloudwatch.MathExpression(
                expression="(errors / invocations) * 100",
                using_metrics={
                    "errors": fn.metric_errors(period=Duration.minutes(5)),
                    "invocations": fn.metric_invocations(period=Duration.minutes(5)),
                },
                period=Duration.minutes(5),
            )
            cloudwatch.Alarm(
                self,
                f"{id_prefix}ErrorRateAlarm",
                metric=error_rate,
                threshold=10,  # percent
                evaluation_periods=1,
                # No invocations in a period means no error-rate data point at all
                # (not zero) — treating that as non-breaching avoids false alarms on
                # a Lambda that's simply been idle.
                treat_missing_data=cloudwatch.TreatMissingData.NOT_BREACHING,
                alarm_description=f"{id_prefix} error rate above 10% over 5 minutes",
            )
            cloudwatch.Alarm(
                self,
                f"{id_prefix}DurationAlarm",
                metric=fn.metric_duration(period=Duration.minutes(5), statistic="p99"),
                threshold=timeout.to_milliseconds() * 0.8,
                evaluation_periods=1,
                treat_missing_data=cloudwatch.TreatMissingData.NOT_BREACHING,
                alarm_description=f"{id_prefix} p99 duration above 80% of its {timeout.to_seconds()}s timeout",
            )

        for id_prefix, (fn, timeout) in pipeline_lambdas.items():
            add_lambda_alarms(fn, id_prefix, timeout)

        # DLQ depth alarms (PLAN.md Phase 12.3): unlike the error-rate alarms above,
        # this fires on *any* accumulation (threshold=1) — a message in a DLQ means
        # automatic retries were already exhausted, so there's nothing to average
        # against a volume baseline the way error-rate is; even one message is
        # something worth a human looking at.
        for id_prefix, dlq in (("ExtractDlq", extract_dlq), ("EmbedDlq", embed_dlq)):
            cloudwatch.Alarm(
                self,
                f"{id_prefix}DepthAlarm",
                metric=dlq.metric_approximate_number_of_messages_visible(period=Duration.minutes(5)),
                threshold=1,
                evaluation_periods=1,
                treat_missing_data=cloudwatch.TreatMissingData.NOT_BREACHING,
                alarm_description=f"{id_prefix} has messages — automatic retries were exhausted",
            )

        # --- Dashboard (PLAN.md Phase 9.4) ---
        dashboard = cloudwatch.Dashboard(self, "PipelineDashboard", dashboard_name="JobPulse-Pipeline")
        dashboard.add_widgets(
            cloudwatch.GraphWidget(
                title="Lambda Invocations",
                left=[fn.metric_invocations() for fn, _ in pipeline_lambdas.values()],
            ),
            cloudwatch.GraphWidget(
                title="Lambda Errors",
                left=[fn.metric_errors() for fn, _ in pipeline_lambdas.values()],
            ),
        )
        dashboard.add_widgets(
            cloudwatch.GraphWidget(
                title="Lambda Duration (p99)",
                left=[fn.metric_duration(statistic="p99") for fn, _ in pipeline_lambdas.values()],
            ),
            cloudwatch.GraphWidget(
                title="DynamoDB Capacity + Throttles",
                left=[
                    postings_table.metric_consumed_read_capacity_units(),
                    postings_table.metric_consumed_write_capacity_units(),
                ],
                right=[
                    postings_table.metric_throttled_requests_for_operations(
                        operations=[
                            dynamodb.Operation.PUT_ITEM,
                            dynamodb.Operation.UPDATE_ITEM,
                            dynamodb.Operation.QUERY,
                        ]
                    )
                ],
            ),
        )
        # Custom EMF metrics emitted by common/metrics.py (PLAN.md Phase 9.2's named
        # examples: postings ingested, extraction failures, average score, alerts sent).
        dashboard.add_widgets(
            cloudwatch.GraphWidget(
                title="Postings Ingested",
                left=[cloudwatch.Metric(namespace="JobPulse", metric_name="PostingsIngested", statistic="Sum")],
            ),
            cloudwatch.GraphWidget(
                title="Extraction Failures",
                left=[cloudwatch.Metric(namespace="JobPulse", metric_name="ExtractionFailures", statistic="Sum")],
            ),
            cloudwatch.GraphWidget(
                title="Average Posting Score",
                left=[cloudwatch.Metric(namespace="JobPulse", metric_name="PostingScore", statistic="Average")],
            ),
            cloudwatch.GraphWidget(
                title="Alerts Sent",
                left=[cloudwatch.Metric(namespace="JobPulse", metric_name="AlertsSent", statistic="Sum")],
            ),
        )
        # DLQ depth (PLAN.md Phase 12) — same metric the alarms above watch, surfaced
        # visually so a growing queue is visible on the dashboard before it trips one.
        dashboard.add_widgets(
            cloudwatch.GraphWidget(
                title="DLQ Depth",
                left=[
                    extract_dlq.metric_approximate_number_of_messages_visible(),
                    embed_dlq.metric_approximate_number_of_messages_visible(),
                ],
            ),
        )

        self.raw_postings_bucket = raw_postings_bucket
        self.postings_table = postings_table
        self.common_layer = common_layer
        self.pydantic_layer = pydantic_layer
        self.fetch_lambda = fetch_lambda
        self.extract_lambda = extract_lambda
        self.extract_dlq = extract_dlq
        self.embed_lambda = embed_lambda
        self.embed_dlq = embed_dlq
        self.alerts_topic = alerts_topic
        self.threshold_lambda = threshold_lambda
        self.alert_email_lambda = alert_email_lambda
        self.query_api_lambda = query_api_lambda
        self.query_api = query_api
        self.dlq_redrive_lambda = dlq_redrive_lambda
