import re
import shutil
import subprocess
import sys
from pathlib import Path

from aws_cdk import (
    Duration,
    RemovalPolicy,
    Stack,
)
from aws_cdk import (
    aws_dynamodb as dynamodb,
)
from aws_cdk import (
    aws_events as events,
)
from aws_cdk import (
    aws_events_targets as targets,
)
from aws_cdk import (
    aws_iam as iam,
)
from aws_cdk import (
    aws_lambda as _lambda,
)
from aws_cdk import (
    aws_lambda_event_sources as lambda_event_sources,
)
from aws_cdk import (
    aws_s3 as s3,
)
from aws_cdk import (
    aws_s3_notifications as s3n,
)
from aws_cdk import (
    aws_sns as sns,
)
from aws_cdk import (
    aws_sns_subscriptions as sns_subscriptions,
)
from constructs import Construct

REPO_ROOT = Path(__file__).resolve().parents[2]
LAMBDAS_DIR = REPO_ROOT / "lambdas"
LAYER_BUILD_ROOT = Path(__file__).resolve().parent / ".layer_build"

DEFAULT_BEDROCK_MODEL_ID = "anthropic.claude-3-5-sonnet-20241022-v2:0"
DEFAULT_BEDROCK_EMBEDDING_MODEL_ID = "amazon.titan-embed-text-v2:0"
DEFAULT_FIT_THRESHOLD = "0.7"

# Placeholders — SES sandbox requires both verified before alerts actually deliver.
# Override at deploy time (e.g. via CDK context) with your own addresses. See
# SETUP.md for the manual SES verification step this requires.
DEFAULT_SENDER_EMAIL = "alerts@example.com"
DEFAULT_RECIPIENT_EMAIL = "candidate@example.com"

# Mirrors common/dynamodb.py's key schema constants. Not imported directly: the CDK app
# runs in infra/.venv, a separate Python environment from the root venv that doesn't
# have common's dependencies (pydantic) installed — infra intentionally doesn't depend
# on application code, only on the plain strings that make up the table's key schema.
PARTITION_KEY = "posting_id"
GSI_NAME = "ScoreIndex"
GSI_PARTITION_KEY = "gsi_pk"
GSI_SORT_KEY = "score"


def _pinned_version(package: str) -> str:
    """Read a package's pinned version out of the root requirements.txt, so the Lambda
    layer we build for it can never silently drift from what's pinned for local dev.
    """
    requirements = (REPO_ROOT / "requirements.txt").read_text()
    match = re.search(rf"^{re.escape(package)}==([^\s;]+)", requirements, re.MULTILINE)
    if not match:
        raise ValueError(f"{package} is not pinned in requirements.txt")
    return match.group(1)


def _build_common_layer_asset() -> str:
    """Copy common/*.py (+ example JSON) and ml/features.py into a Lambda-layer-shaped
    python/ dir.

    A plain file copy, not pip/Docker bundling: common/storage_keys.py has no
    third-party dependency, so it's safe to ship as-is. common/models.py imports
    pydantic, but that import is only exercised by whichever Lambda actually does
    `from common.models import ...` (common/__init__.py has no eager imports) — a Lambda
    that needs it also attaches the PydanticLayer built below.

    ml/features.py (PLAN.md Phase 6) is included too, but deliberately *only* that one
    file, not the rest of ml/ — ml/train.py, ml/dataset.py etc. import scikit-learn/
    xgboost, and features.py itself is pure stdlib beyond `common.models`, so copying
    just it (plus ml/__init__.py to make it a package) gives the threshold Lambda
    (Phase 7) the exact same feature computation training used, without pulling any of
    training's heavy dependencies into the Lambda.
    """
    build_dir = LAYER_BUILD_ROOT / "common"
    python_dir = build_dir / "python"
    common_dir = python_dir / "common"
    ml_dir = python_dir / "ml"
    for existing in (common_dir, ml_dir):
        if existing.exists():
            shutil.rmtree(existing)
    common_dir.mkdir(parents=True)
    ml_dir.mkdir(parents=True)

    for pattern in ("*.py", "*.json"):
        for file_path in (REPO_ROOT / "common").glob(pattern):
            shutil.copy(file_path, common_dir / file_path.name)
    for filename in ("__init__.py", "features.py"):
        shutil.copy(REPO_ROOT / "ml" / filename, ml_dir / filename)

    return str(build_dir)


def _build_threshold_lambda_asset() -> str:
    """Stage lambdas/threshold/*.py plus the trained re-ranker's inference JSON into one
    deployable directory.

    The inference JSON (ml/artifacts/reranker_inference.json) is a training *output*,
    gitignored and regenerated by `python -m ml.train` — it must exist before `cdk
    synth`/`cdk deploy` runs, the same "train offline, deploy the artifact" precondition
    any real ML deployment pipeline has. Its path is hardcoded here rather than imported
    from ml.train (which would pull scikit-learn/xgboost into the infra venv — the same
    dependency-isolation reason the DynamoDB key-schema constants above are duplicated
    rather than imported from common.dynamodb).
    """
    inference_json_path = REPO_ROOT / "ml" / "artifacts" / "reranker_inference.json"
    if not inference_json_path.exists():
        raise FileNotFoundError(
            f"{inference_json_path} not found — run `python -m ml.train` (from the repo "
            "root, with the root .venv active) to train the re-ranker before deploying."
        )

    build_dir = LAYER_BUILD_ROOT / "threshold_lambda"
    if build_dir.exists():
        shutil.rmtree(build_dir)
    build_dir.mkdir(parents=True)

    for file_path in (LAMBDAS_DIR / "threshold").glob("*.py"):
        shutil.copy(file_path, build_dir / file_path.name)
    shutil.copy(inference_json_path, build_dir / "model.json")

    return str(build_dir)


def _build_pydantic_layer_asset() -> str:
    """Download pydantic (+ its compiled pydantic-core dependency) as Lambda-compatible
    manylinux wheels, without Docker.

    pydantic-core ships as a platform-specific compiled wheel (it's written in Rust).
    Building it locally with a plain `pip install --target` on a Mac would silently
    bundle a macOS binary that crashes on Lambda's Linux runtime. Instead, `pip install
    --platform manylinux2014_x86_64 --only-binary=:all:` downloads the prebuilt Linux
    wheel straight from PyPI — no compilation, no Docker — as long as one exists for the
    pinned version (it does for pydantic 2.x). Cached by pinned version so `cdk synth`
    doesn't re-download on every run.
    """
    version = _pinned_version("pydantic")
    build_dir = LAYER_BUILD_ROOT / "pydantic"
    marker = build_dir / f".built-{version}"
    if marker.exists():
        return str(build_dir)

    python_dir = build_dir / "python"
    if python_dir.exists():
        shutil.rmtree(python_dir)
    python_dir.mkdir(parents=True)

    subprocess.run(
        [
            sys.executable,
            "-m",
            "pip",
            "install",
            f"pydantic=={version}",
            "--platform",
            "manylinux2014_x86_64",
            "--implementation",
            "cp",
            "--python-version",
            "3.12",
            "--only-binary=:all:",
            "--target",
            str(python_dir),
        ],
        check=True,
        capture_output=True,
    )
    marker.touch()
    return str(build_dir)


class JobPulseStack(Stack):
    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        # --- Raw postings landing zone (PLAN.md Phase 2.2) ---
        # Immutable audit trail: every posting a source returns lands here untouched,
        # keyed by common.storage_keys.raw_posting_key. Also holds the extraction
        # Lambda's structured/ output (PLAN.md Phase 3) until Phase 5 adds DynamoDB.
        raw_postings_bucket = s3.Bucket(
            self,
            "RawPostingsBucket",
            removal_policy=RemovalPolicy.DESTROY,  # dev default; use RETAIN in prod
            auto_delete_objects=True,
            block_public_access=s3.BlockPublicAccess.BLOCK_ALL,
        )

        # --- Structured store (PLAN.md Phase 5) ---
        # Stream enabled so the embed Lambda can react to newly-extracted postings
        # (NEW_IMAGE is enough — embed only needs the item's current field values, not
        # what changed). PAY_PER_REQUEST: postings/day volume is low and spiky (bursts
        # on each 6-hour ingestion cycle), not steady enough to right-size provisioned
        # capacity for.
        postings_table = dynamodb.Table(
            self,
            "PostingsTable",
            partition_key=dynamodb.Attribute(
                name=PARTITION_KEY, type=dynamodb.AttributeType.STRING
            ),
            billing_mode=dynamodb.BillingMode.PAY_PER_REQUEST,
            removal_policy=RemovalPolicy.DESTROY,  # dev default; use RETAIN in prod
            stream=dynamodb.StreamViewType.NEW_IMAGE,
        )
        postings_table.add_global_secondary_index(
            index_name=GSI_NAME,
            partition_key=dynamodb.Attribute(
                name=GSI_PARTITION_KEY, type=dynamodb.AttributeType.STRING
            ),
            sort_key=dynamodb.Attribute(name=GSI_SORT_KEY, type=dynamodb.AttributeType.NUMBER),
            projection_type=dynamodb.ProjectionType.ALL,
        )

        # --- Shared data-contracts layer, consumed by every Lambda (Phase 1 code) ---
        common_layer = _lambda.LayerVersion(
            self,
            "CommonLayer",
            code=_lambda.Code.from_asset(_build_common_layer_asset()),
            compatible_runtimes=[_lambda.Runtime.PYTHON_3_12],
            description="Shared JobPulse data contracts (common/ package)",
        )

        # --- Third-party dependency layer, for Lambdas that need common.models ---
        pydantic_layer = _lambda.LayerVersion(
            self,
            "PydanticLayer",
            code=_lambda.Code.from_asset(_build_pydantic_layer_asset()),
            compatible_runtimes=[_lambda.Runtime.PYTHON_3_12],
            compatible_architectures=[_lambda.Architecture.X86_64],
            description="pydantic + pydantic-core (manylinux x86_64 wheels)",
        )

        # --- Ingestion Lambda (PLAN.md Phase 2.1) ---
        fetch_lambda = _lambda.Function(
            self,
            "FetchLambda",
            runtime=_lambda.Runtime.PYTHON_3_12,
            architecture=_lambda.Architecture.X86_64,
            handler="handler.handler",
            code=_lambda.Code.from_asset(str(LAMBDAS_DIR / "fetch")),
            layers=[common_layer],
            timeout=Duration.seconds(30),
            memory_size=256,
            environment={
                "RAW_BUCKET_NAME": raw_postings_bucket.bucket_name,
                "JOB_SOURCE": "remoteok",
            },
        )
        raw_postings_bucket.grant_write(fetch_lambda)

        # --- Scheduled trigger (PLAN.md Phase 2.3) ---
        events.Rule(
            self,
            "FetchScheduleRule",
            schedule=events.Schedule.rate(Duration.hours(6)),
            targets=[targets.LambdaFunction(fetch_lambda)],
        )

        # --- Extraction Lambda (PLAN.md Phase 3) ---
        extract_lambda = _lambda.Function(
            self,
            "ExtractLambda",
            runtime=_lambda.Runtime.PYTHON_3_12,
            architecture=_lambda.Architecture.X86_64,
            handler="handler.handler",
            code=_lambda.Code.from_asset(str(LAMBDAS_DIR / "extract")),
            layers=[common_layer, pydantic_layer],
            timeout=Duration.seconds(60),  # allows for the Bedrock call + one retry
            memory_size=512,
            environment={
                "BEDROCK_MODEL_ID": DEFAULT_BEDROCK_MODEL_ID,
                "POSTINGS_TABLE_NAME": postings_table.table_name,
            },
        )
        # Least privilege: read only the raw/ prefix it consumes from S3. It only ever
        # creates new DynamoDB items (one per posting_id, set once at extraction time),
        # never reads or modifies an existing one — PutItem only, not grant_write_data's
        # broader PutItem/UpdateItem/DeleteItem/BatchWriteItem set.
        extract_lambda.add_to_role_policy(
            iam.PolicyStatement(
                actions=["s3:GetObject"],
                resources=[raw_postings_bucket.arn_for_objects("raw/*")],
            )
        )
        extract_lambda.add_to_role_policy(
            iam.PolicyStatement(
                actions=["dynamodb:PutItem"],
                resources=[postings_table.table_arn],
            )
        )
        extract_lambda.add_to_role_policy(
            iam.PolicyStatement(
                actions=["bedrock:InvokeModel"],
                resources=[
                    f"arn:aws:bedrock:{self.region}::foundation-model/anthropic.*"
                ],
            )
        )

        # --- Event-driven trigger: new raw posting -> extract (PLAN.md Phase 3) ---
        raw_postings_bucket.add_event_notification(
            s3.EventType.OBJECT_CREATED,
            s3n.LambdaDestination(extract_lambda),
            s3.NotificationKeyFilter(prefix="raw/", suffix=".json"),
        )

        # --- Embedding Lambda (PLAN.md Phase 4, trigger + persistence updated in Phase 5) ---
        embed_lambda = _lambda.Function(
            self,
            "EmbedLambda",
            runtime=_lambda.Runtime.PYTHON_3_12,
            architecture=_lambda.Architecture.X86_64,
            handler="handler.handler",
            code=_lambda.Code.from_asset(str(LAMBDAS_DIR / "embed")),
            layers=[common_layer, pydantic_layer],
            timeout=Duration.seconds(60),
            memory_size=512,
            environment={
                "BEDROCK_EMBEDDING_MODEL_ID": DEFAULT_BEDROCK_EMBEDDING_MODEL_ID,
                "POSTINGS_TABLE_NAME": postings_table.table_name,
                "RAW_BUCKET_NAME": raw_postings_bucket.bucket_name,
            },
        )
        # Least privilege: only the candidate/ cache prefix needs S3 access now — the
        # posting itself arrives via the DynamoDB stream, and the embedding/similarity
        # go back via UpdateItem, not an S3 write.
        embed_lambda.add_to_role_policy(
            iam.PolicyStatement(
                actions=["s3:GetObject", "s3:PutObject"],
                resources=[raw_postings_bucket.arn_for_objects("candidate/*")],
            )
        )
        # UpdateItem only, not PutItem: this Lambda only ever patches a row extraction
        # already created, never creates one — the exact inverse of extraction's grant.
        embed_lambda.add_to_role_policy(
            iam.PolicyStatement(
                actions=["dynamodb:UpdateItem"],
                resources=[postings_table.table_arn],
            )
        )
        embed_lambda.add_to_role_policy(
            iam.PolicyStatement(
                actions=["bedrock:InvokeModel"],
                resources=[
                    f"arn:aws:bedrock:{self.region}::foundation-model/amazon.titan-embed*"
                ],
            )
        )

        # --- Event-driven trigger: new posting row -> embed (PLAN.md Phase 5) ---
        # INSERT-only filter: this Lambda's own UpdateItem calls produce MODIFY stream
        # records, which the filter excludes, so it can never re-trigger itself.
        # add_event_source also grants the stream-read permissions (DescribeStream,
        # GetRecords, GetShardIterator, ListStreams) automatically.
        embed_lambda.add_event_source(
            lambda_event_sources.DynamoEventSource(
                postings_table,
                starting_position=_lambda.StartingPosition.LATEST,
                batch_size=1,
                retry_attempts=2,
                filters=[
                    _lambda.FilterCriteria.filter(
                        {"eventName": _lambda.FilterRule.is_equal("INSERT")}
                    )
                ],
            )
        )

        # --- Alerts topic (PLAN.md Phase 7.2) ---
        # A separate SNS topic (rather than the threshold Lambda calling SES directly)
        # is what makes "later, an additional subscriber" (spec section 5.3 — e.g. a
        # future Slack/Discord webhook) free: it would attach to this same topic without
        # touching the threshold Lambda or the alert_email Lambda below at all.
        alerts_topic = sns.Topic(self, "AlertsTopic", display_name="JobPulse fit alerts")

        # --- Scoring + threshold Lambda (PLAN.md Phase 7.1) ---
        threshold_lambda = _lambda.Function(
            self,
            "ThresholdLambda",
            runtime=_lambda.Runtime.PYTHON_3_12,
            architecture=_lambda.Architecture.X86_64,
            handler="handler.handler",
            code=_lambda.Code.from_asset(_build_threshold_lambda_asset()),
            layers=[common_layer, pydantic_layer],
            timeout=Duration.seconds(30),
            memory_size=256,
            environment={
                "POSTINGS_TABLE_NAME": postings_table.table_name,
                "ALERTS_TOPIC_ARN": alerts_topic.topic_arn,
                "FIT_THRESHOLD": DEFAULT_FIT_THRESHOLD,
            },
        )
        # UpdateItem only — same reasoning as the embed Lambda's grant above.
        threshold_lambda.add_to_role_policy(
            iam.PolicyStatement(
                actions=["dynamodb:UpdateItem"],
                resources=[postings_table.table_arn],
            )
        )
        alerts_topic.grant_publish(threshold_lambda)

        # --- Event-driven trigger: embedding just landed -> threshold (PLAN.md Phase 7) ---
        # This Lambda must run *after* embed (it needs embedding_similarity as a
        # feature) but embed's own write is also a MODIFY — eventName alone can't tell
        # "embed just finished" apart from "threshold already finished" the way
        # INSERT-vs-MODIFY could in Phase 5. The extra conditions do that instead:
        # `embedding` (a Binary attribute) existing means embed has run; `score` still
        # being NULL means threshold hasn't. Once threshold sets a real score, this
        # same filter excludes its own MODIFY — no self-trigger, same principle as
        # Phase 5's embed trigger, expressed with a finer-grained filter.
        threshold_lambda.add_event_source(
            lambda_event_sources.DynamoEventSource(
                postings_table,
                starting_position=_lambda.StartingPosition.LATEST,
                batch_size=1,
                retry_attempts=2,
                filters=[
                    _lambda.FilterCriteria.filter(
                        {
                            "eventName": ["MODIFY"],
                            "dynamodb": {
                                "NewImage": {
                                    "embedding": {"B": [{"exists": True}]},
                                    "score": {"NULL": [True]},
                                }
                            },
                        }
                    )
                ],
            )
        )

        # --- Alert email Lambda (PLAN.md Phase 7.2-3) ---
        # No layers: pure stdlib + boto3 (SES), no common/pydantic dependency at all.
        alert_email_lambda = _lambda.Function(
            self,
            "AlertEmailLambda",
            runtime=_lambda.Runtime.PYTHON_3_12,
            architecture=_lambda.Architecture.X86_64,
            handler="handler.handler",
            code=_lambda.Code.from_asset(str(LAMBDAS_DIR / "alert_email")),
            timeout=Duration.seconds(15),
            memory_size=128,
            environment={
                "SENDER_EMAIL": self.node.try_get_context("senderEmail") or DEFAULT_SENDER_EMAIL,
                "RECIPIENT_EMAIL": self.node.try_get_context("recipientEmail")
                or DEFAULT_RECIPIENT_EMAIL,
            },
        )
        # SES has no per-identity resource ARN known until an identity is manually
        # verified (see SETUP.md), so this is scoped to the action rather than a
        # specific identity resource.
        alert_email_lambda.add_to_role_policy(
            iam.PolicyStatement(actions=["ses:SendEmail", "ses:SendRawEmail"], resources=["*"])
        )
        alerts_topic.add_subscription(sns_subscriptions.LambdaSubscription(alert_email_lambda))

        self.raw_postings_bucket = raw_postings_bucket
        self.postings_table = postings_table
        self.common_layer = common_layer
        self.pydantic_layer = pydantic_layer
        self.fetch_lambda = fetch_lambda
        self.extract_lambda = extract_lambda
        self.embed_lambda = embed_lambda
        self.alerts_topic = alerts_topic
        self.threshold_lambda = threshold_lambda
        self.alert_email_lambda = alert_email_lambda
